version: "3.3"

services:
  product-service:
    build: ./products
    image: chenv/products:v1.0.0
    ports:
      - 5001:3000

  application:
    build: ./application
    image: chenv/application:v1.0.0
    ports:
      - 5000:80
    depends_on:
      - product-service